name: Python CI/CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: Test e Linting
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Lint with pylint
        run: |
          # Disabilitiamo gli avvisi di stile per non far fallire la build
          pylint --disable=C0114,C0116,C0301,C0303,C0304,C0411,R1725,C0103,W0612,R0914,R0915,R0912,R0801,R0402 src/

      - name: Test with pytest
        run: |
          pytest

  # JOB 2: Build e Push su Docker Hub
  build-and-push:
    name: Build and Push Docker Image
    # Dipendenza: Esegui questo job solo se 'test' ha successo
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Assicurati che il nome sia corretto: tuo-username/nome-progetto:versione
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-sign-language-project:latest
